


################### DATASET CLEANING #######################

## Area to filter
## Considering pictures 1024*1024, bbox smaller then 0.1% of the area or greater then 80% of the area are not to be considered

min_area: 1048.576
max_area: 996147.2


## Dataset path and config

train_csv_path: Datasets/global-wheat-detection/global-wheat-detection/train_cleaned.csv
image_path: Datasets/global-wheat-detection/global-wheat-detection/train/
log_dir: logs/
checkpoint_path: checkpoints/
batch_size: 1

## Training params

early_stopping_patience: 5
epochs: 25

restore_from_checkpoint: False


## model config


conv_out_channels: [32, 64, 128]
kernel_sizes: [3, 3, 3]